Document: btk-core
Title: Debian btk-core Manual
Author: <insert document author here>
Abstract: This manual describes what btk-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/btk-core/btk-core.sgml.gz

Format: postscript
Files: /usr/share/doc/btk-core/btk-core.ps.gz

Format: text
Files: /usr/share/doc/btk-core/btk-core.text.gz

Format: HTML
Index: /usr/share/doc/btk-core/html/index.html
Files: /usr/share/doc/btk-core/html/*.html
